baseurl: "/museum"
url: "https://yprits.github.io"
title: "Моя коллекция"
remote_theme: pages-themes/hacker@v0.2.0
collections:
  exhibits:
    output: true
    permalink: /:collection/:name/
  models:
    output: true
    permalink: /:collection/:name/
  pgs:
    output: true
    permalink: /:collection/:name/
  ephemera:
    output: true
    permalink: /:collection/:name/
  literature:
    output: true
    permalink: /:collection/:name/

defaults:
- scope:
      path: "_exhibits"
      type: exhibits
  values:
    model: "не указана"
    category: "прочее"
    prodyear: "не указан"
    modelyears: "неизвестны"
    serial: "-"
    manufacturer: "неизвестен"
    country: "неизвестна"
    price: "не указана"
    condition: "не проверено"
- scope:
      path: "_models"
      type: models
  values:
      status: "ПОИСК"

